name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows x86_64
          - target: x86_64-pc-windows-gnu
            artifact_name: env_checker.exe
          # Windows ARM64
          - target: aarch64-pc-windows-gnullvm
            artifact_name: env_checker.exe
          # Linux x86_64
          - target: x86_64-unknown-linux-gnu
            artifact_name: env_checker
          # Linux ARM64
          - target: aarch64-unknown-linux-gnu
            artifact_name: env_checker
          # macOS x86_64
          - target: x86_64-apple-darwin
            artifact_name: env_checker
          # macOS ARM64
          - target: aarch64-apple-darwin
            artifact_name: env_checker

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: install aarch64-w64-mingw32-clang on windows arm64
        if: matrix.target == 'aarch64-pc-windows-gnullvm'
        run: |
          winget install LLVM.LLVM

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
